created my builder page
BuidlGuidl/batch11.buidlguidl.com pull request #21
Opened 2024-11-20 21:56 UTC by AbolareRoheemah

## Description

_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

2024-11-21 06:33 UTC, phipsae requested changes
@AbolareRoheemah Thank you so much for your nice page! You’ve put a lot of effort into it, and it’s refreshing to see something that stands out from the typical personal pages.

In general for PRs, please make sure to fill out the description, so that a reviewers knows what you have implemented. Including a screenshot of what you’ve built is highly recommended, and for more complex PRs, adding a short video can be very helpful.

I’ve added some comments below for your review.

Thanks again!

2024-11-21 06:33 UTC, phipsae commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
> +import React from "react";
You don't need to explicitly import React in Next.js anymore, starting from Next.js 12.2 and React 17 and above. With these versions, Next.js automatically imports React when needed, so you can safely omit import React from "react" at the top of your files.

2024-11-21 06:33 UTC, phipsae commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
Pls make sure there are no errors thrown in the console. To have a look in the console is also good since you get direct feedback to your code. Also somehow to mobile responsiveness doesn't work correctly, pls doublecheck.  

Additionally there are tags like `<h1>` visible.

<img width="629" alt="Screenshot 2024-11-21 at 14 17 02" src="https://github.com/user-attachments/assets/abd52dff-ef66-42b9-9f8d-5b633d7ab607">

2024-11-21 06:33 UTC, phipsae commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
> +"use client";
You don't need to use "use client" here, as this can be server-rendered. There are no client-side actions like useEffect or useState involved.

2024-11-21 06:33 UTC, phipsae commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
> +export default function RoheemahBuilderPage() {
For a Next.js page component, we should follow Next.js conventions, to have a component of type `NextPage`.

2024-11-21 06:33 UTC, phipsae commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
> +              <div className="mt-6 text-[#9B9EA1]">
Inside this `<div>` there is a lot of receptive code, maybe you could refactor it?

2024-11-21 06:33 UTC, phipsae commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
> +              </div>
A lot of repetition, could you make it cleaner?

2024-11-21 06:33 UTC, phipsae commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
> +            </div>
Repetition here again, would could you do?

2024-11-22 23:20 UTC, AbolareRoheemah commented
> @AbolareRoheemah Thank you so much for your nice page! You’ve put a lot of effort into it, and it’s refreshing to see something that stands out from the typical personal pages.
> 
> In general for PRs, please make sure to fill out the description, so that a reviewers knows what you have implemented. Including a screenshot of what you’ve built is highly recommended, and for more complex PRs, adding a short video can be very helpful.
> 
> I’ve added some comments below for your review.
> 
> Thanks again!

Noted @phipsae. Thanks for the kind words

2024-11-22 23:47 UTC, AbolareRoheemah commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
The h1 tags were intended to be like that. Its part of the styling @phipsae

2024-11-24 03:03 UTC, phipsae requested changes
Thanks for the changes! 

Find below some comments. And please have a look at the mobile responsiveness. 
And then we merge.

2024-11-24 03:03 UTC, phipsae commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
> +                            </div> */}
Remove

2024-11-24 03:03 UTC, phipsae commented on packages/nextjs/app/builders/0x21dfd1CfD1d45801f46B0F40Aed056b064045aA2/page.tsx
> +                  { icon: "link", text: "abolareroheemah@gmail.com" },
You might want to add a link here to open email editor?

2024-11-27 04:00 UTC, phipsae requested changes
We are almost ready to merge, your page looks great! 

The only remaining task is to ensure there are no changes to `yarn.lock`

2024-11-27 04:00 UTC, phipsae commented on yarn.lock
This file shouldn't be changed, since you don't use any new libraries for your personal page.

2024-11-27 19:39 UTC, AbolareRoheemah commented
> We are almost ready to merge, your page looks great!
> 
> The only remaining task is to ensure there are no changes to `yarn.lock`

Thanks @phipsae and sorry for the stress

The only way I can think of to achieve this is to copy the yarn.lock file on the main branch and replace it with what I have in my own branch. Hope this is fine coz when I run git pull origin master, it tells me "already up to date".

2024-11-28 06:42 UTC, phipsae commented
> > We are almost ready to merge, your page looks great!
> > The only remaining task is to ensure there are no changes to `yarn.lock`
> 
> Thanks @phipsae and sorry for the stress
> 
> The only way I can think of to achieve this is to copy the yarn.lock file on the main branch and replace it with what I have in my own branch. Hope this is fine coz when I run git pull origin master, it tells me "already up to date".

No worries, that's why you here :) 

You could run `git checkout main -- yarn.lock`, then commit and push.

2024-11-28 06:59 UTC, AbolareRoheemah commented
> git checkout main -- yarn.lock



> > > We are almost ready to merge, your page looks great!
> > > The only remaining task is to ensure there are no changes to `yarn.lock`
> > 
> > 
> > Thanks @phipsae and sorry for the stress
> > The only way I can think of to achieve this is to copy the yarn.lock file on the main branch and replace it with what I have in my own branch. Hope this is fine coz when I run git pull origin master, it tells me "already up to date".
> 
> No worries, that's why you here :)
> 
> You could run `git checkout main -- yarn.lock`, then commit and push.
> 
> So you can get the yarn.lock version from main.

Alright @phipsae. Done and pushed

2024-11-28 07:41 UTC, phipsae commented
Perfect, it worked! Let merge

2024-11-28 07:41 UTC, merged