3. Fevicon,Logo,Subtitle Chnaged
BuidlGuidl/batch11.buidlguidl.com pull request #24
Opened 2024-11-28 10:52 UTC by Vedant-05

## Description

Have updated the fevicon & logo to the new batch 11 Logo , changed Subtitle to batch 11's moto, added an SVG icon for the subtitle. Attaching the ss for the same .

New Logo:
![logo](https://github.com/user-attachments/assets/914e8d80-4772-4e37-8c32-39d04a5a66f8)

Current Batch 11 Header
<img width="1710" alt="Screenshot 2024-11-28 at 4 20 23 PM" src="https://github.com/user-attachments/assets/3b4c1eb9-34c5-4d69-a5fc-7b2aa90a87f6">

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #8_

Your ENS/address:
0xc4Ad6218B68514161fFeC5dA54E1D30462C27CCD

2024-11-28 10:57 UTC, Vedant-05 commented
Should we change the title of the page also from "Scaffold-ETH 2 App" to "BuidlGuidl-Batch-11" ??

2024-11-29 05:59 UTC, phipsae requested changes
Nice logo! Thanks for the PR. 

Just a little request below :)

2024-11-29 05:59 UTC, phipsae commented on packages/nextjs/components/Header.tsx
It would also be great to update the title in `layout.tsx` from "Scaffold-ETH 2 App" to something more relevant to Batch 11.

2024-11-29 06:02 UTC, Vedant-05 commented on packages/nextjs/components/Header.tsx
Yeah i added it in the comment that should I change it too "BuidlGuidl-Batch-11" ?

2024-11-29 06:07 UTC, phipsae commented on packages/nextjs/components/Header.tsx
Yes, would be nice

2024-11-29 06:08 UTC, Vedant-05 commented on packages/nextjs/components/Header.tsx
ok on it !

2024-11-29 06:12 UTC, Vedant-05 commented
I have chnaged the title for the website , and committed it to this pr , can you review it once ?

2024-11-29 06:25 UTC, phipsae commented
Thanks! Lets merge

2024-11-29 06:25 UTC, merged

2024-11-29 06:46 UTC, phipsae commented
Could you please merge with latest main branch and push again. We ran in some weird eslint error while deploying to vercel (has nothing to do with your code).

2024-11-29 06:54 UTC, Vedant-05 commented
Hey sorry i didn't get you ,
Do i need to take a pull from the repo , then merge my title one branch in my fork repos main branch and then create a new pull request to the main repo's main branch ?

2024-11-29 06:59 UTC, phipsae commented
Or maybe could you try to push that again to github first?