create the CanvasOnchain contract and write the test
BuidlGuidl/batch11.buidlguidl.com pull request #31
Opened 2024-12-04 11:33 UTC by Abidoyesimze

## Description

_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

2024-12-04 13:21 UTC, melanke commented on packages/hardhat/contracts/CanvasOnchain.sol
> +    }
Well, we could override a pixel anyway, but, why erase? And without an event...

2024-12-04 13:37 UTC, Abidoyesimze commented on packages/hardhat/contracts/CanvasOnchain.sol
> +    }
Okay will make changes for that

2024-12-04 14:02 UTC, Abidoyesimze commented on packages/hardhat/contracts/CanvasOnchain.sol
> +    }
> Well, we could override a pixel anyway, but, why erase? And without an event...

I have remove the reset pixel functionality

2024-12-04 20:55 UTC, melanke approved these changes

2024-12-04 20:56 UTC, melanke requested changes
We need the deployment script, right?

2024-12-05 04:09 UTC, Abidoyesimze commented
> We need the deployment script, right?

Ohhhh yes but i don't know if we are deploying it to optimism mainnet that's why i haven't deploy it yet

2024-12-05 04:13 UTC, Abidoyesimze commented
> @Abidoyesimze Nice, a smart contract, thanks!
> 
> Please ensure you include a description for your PR. As a rule of thumb, always provide a proper description when creating a PR, it’s essential for collaboration.
> 
> Please give the branch always a dedicated name, what you want to implement. `smize` doesn't tell me anything and I think it was the same before for your personal page.
> 
> Sorry to stress that, but thats what we try to teach you here in the batch program. Pls fix this first, then I will have a look at your code.
> 
> And a deployment script would be nice. As soon as you have it deployed you can add the ABI to the `externalContract.ts` file in next.js. Then it is shown in the debug page.

Sure, i'll make changes to the branch name but are we deploying the contract to optimism mainnet

2024-12-05 04:19 UTC, closed without merging